'use client';
import { useEffect,useState } from 'react';
import { Zap,Plus,ArrowUp,Code2,Database,Activity,Search,RefreshCw,PenLine,Trash2,Play,ExternalLink,Link2,LogOut,Copy,BookOpen } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel } from '@/components/ui/alert-dialog';
import { Switch } from '@/components/ui/switch';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Skeleton } from '@/components/ui/skeleton';
import { toast,Toaster } from 'sonner';
type Post={id:number;title:string;content:string;published:boolean;owner_id:number;created:string;owner:{email:string}};
type Row={Post:Post;votes:number;voted:boolean};
type Log={method:string;path:string;status:number;ms:number;data:any};
export default function Studio(){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState(''),[mine,setMine]=useState(false),[page,setPage]=useState(0),[persona,setPersona]=useState('1'),[tab,setTab]=useState('posts');
 const [base,setBase]=useState(''),[baseDraft,setBaseDraft]=useState(''),[token,setToken]=useState(''),[user,setUser]=useState<any>(null),[connect,setConnect]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[signup,setSignup]=useState(false);
 const [editor,setEditor]=useState(false),[edit,setEdit]=useState<Post|null>(null),[title,setTitle]=useState(''),[content,setContent]=useState(''),[published,setPublished]=useState(true),[remove,setRemove]=useState<Post|null>(null);
 const [logs,setLogs]=useState<Log[]>([]),[endpoint,setEndpoint]=useState('GET /posts/'),[body,setBody]=useState('{\n  "title": "Hello, API",\n  "content": "My first request.",\n  "published": true\n}'),[resourceId,setResourceId]=useState('1');
 const uid=base?user?.id:Number(persona);
 async function api(path:string,method='GET',payload?:any,override?:{base:string;token:string}){
  const b=override?.base??base,t=override?.token??token,start=performance.now();let data:any,status=0;
  try{const res=await fetch((b||'/api/sandbox')+path,{method,headers:{'Content-Type':payload instanceof URLSearchParams?'application/x-www-form-urlencoded':'application/json',...(b? t?{Authorization:'Bearer '+t}:{}:{'x-persona':persona})},body:payload===undefined?undefined:payload instanceof URLSearchParams?payload.toString():JSON.stringify(payload),signal:AbortSignal.timeout(15000)});status=res.status;const text=await res.text();try{data=text?JSON.parse(text):null}catch{data={detail:text.slice(0,1000)}}if(!res.ok)throw new Error(typeof data?.detail==='string'?data.detail:JSON.stringify(data?.detail||data));return data;
  }catch(e:any){data=data||{detail:e.message};throw e}finally{const safe=path==='/login'?{...data,access_token:data?.access_token?'[redacted]':undefined}:data;setLogs(old=>[{method,path,status,ms:Math.round(performance.now()-start),data:safe},...old].slice(0,30))}
 }
 async function refresh(){if(base&&!token){setRows([]);return}setLoading(true);setError('');try{setRows(await api(`/posts/?limit=12&skip=${page*12}&search=${encodeURIComponent(search)}&mine=${mine}`))}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{const t=setTimeout(refresh,250);return()=>clearTimeout(t)},[base,token,persona,page,search,mine]);
 function compose(p?:Post){setEdit(p||null);setTitle(p?.title||'');setContent(p?.content||'');setPublished(p?.published??true);setEditor(true)}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api(edit?`/posts/${edit.id}`:'/posts/',edit?'PUT':'POST',{title,content,published});setEditor(false);toast.success(edit?'Post updated':'Post created');await refresh()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 async function vote(r:Row){setBusy(true);try{await api('/vote/','POST',{post_id:r.Post.id,dir:r.voted?0:1});await refresh()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 async function sample(){setBusy(true);try{await api('/posts/','POST',{title:'Hello from FastAPI Studio',content:'This is a sample post in your private sandbox. Edit it, vote on it, or switch to the Reader persona to try the ownership rules. Every action makes a real request — inspect the response on the right.',published:true});await refresh()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);try{const url=new URL(baseDraft);if(url.protocol!=='https:')throw Error('Use the HTTPS address of your deployed FastAPI backend.');const b=baseDraft.replace(/\/$/,'');if(signup)await api('/users/','POST',{email,password},{base:b,token:''});const auth=await api('/login','POST',new URLSearchParams({username:email,password}),{base:b,token:''});const u=await api('/users/me','GET',undefined,{base:b,token:auth.access_token});setBase(b);setToken(auth.access_token);setUser(u);setPassword('');setPage(0);setConnect(false);toast.success('Connected to FastAPI')}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 async function run(){setBusy(true);try{const [method,p]=endpoint.split(' ');await api(p.replace('{id}',resourceId),method,['POST','PUT'].includes(method)?JSON.parse(body):undefined);toast.success('Request complete');if(method!=='GET')await refresh()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 const last=logs[0];
 return <div className="studio"><Toaster theme="dark" richColors/><header className="top"><a className="brand" href="/"><span className="brand-icon"><Zap size={22}/></span>fastapi<span className="brand-light">studio</span><span className="version">2.0</span></a><div className="top-right"><span className="env"><Database size={14}/>{base?'Connected FastAPI':'Private sandbox'}</span><a href="https://github.com/kranthivg/fastapi_project" target="_blank" rel="noreferrer" className="repo-link">View repository <ExternalLink size={14}/></a></div></header>
 <main><section className="heading"><div><div className="eyebrow">KRANTHI’S API WORKSPACE</div><h1>Your API. In action<span>.</span></h1><p>Create a post. Cast a vote. See what happens under the hood.</p></div><Button className="connect-button" variant="outline" onClick={()=>setConnect(true)}><Link2 size={16}/>{base?'Connection settings':'Connect FastAPI'}</Button></section>
 <div className="environment"><div><Database size={20}/><div><strong>{base?'Your Python backend':'Hosted playground'}</strong><span>{base?base:'Real saved data · two test personas · isolated to your account'}</span></div></div>{base?<Button variant="ghost" onClick={()=>{setBase('');setToken('');setUser(null);setRows([]);setLogs([])}}><LogOut size={15}/>Disconnect</Button>:<Select value={persona} onValueChange={v=>{setPersona(v);setPage(0)}}><SelectTrigger aria-label="Active sandbox persona"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="1">Author · author@example.com</SelectItem><SelectItem value="2">Reader · reader@example.com</SelectItem></SelectContent></Select>}</div>
 <div className="workspace"><div className="work-main"><Tabs value={tab} onValueChange={setTab}><div className="tab-row"><TabsList variant="line"><TabsTrigger value="posts"><Database/>Posts</TabsTrigger><TabsTrigger value="explorer"><Code2/>API explorer</TabsTrigger><TabsTrigger value="guide"><BookOpen/>Project guide</TabsTrigger></TabsList><span className="muted text-sm">{base?'JWT session':'Worker + D1'}</span></div>
 <TabsContent value="posts"><div className="toolbar"><div className="search"><Search size={17}/><Input aria-label="Search posts" placeholder="Search posts…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/></div><label className="mine"><Switch checked={mine} onCheckedChange={v=>{setMine(v);setPage(0)}}/>My posts</label><Button onClick={()=>compose()} disabled={!!base&&!token}><Plus size={17}/>New post</Button></div>
 {error?<div className="empty"><h2>Couldn’t load posts</h2><p>{error}</p><Button onClick={refresh} variant="outline">Try again</Button></div>:loading?<div className="grid-posts">{[1,2].map(i=><Skeleton key={i} className="h-64 rounded-xl"/>)}</div>:rows.length===0?<div className="empty"><div className="empty-icon"><PenLine size={32}/></div><span className="eyebrow">A CLEAN SLATE</span><h2>{search?'No matching posts':'Make your first request.'}</h2><p>{search?'Try another title.':'Your posts will appear here. Create one to explore the full API flow.'}</p><div className="flex gap-3 justify-center"><Button onClick={()=>compose()}><Plus size={16}/>Create a post</Button>{!base&&!search&&<Button variant="outline" onClick={sample} disabled={busy}>Add sample post</Button>}</div></div>:<div className="grid-posts">{rows.map(r=><article className="post-card" key={r.Post.id}><div className="post-top"><span className={'pill '+(r.Post.published?'published':'draft')}>{r.Post.published?'Published':'Draft'}</span><span className="mono muted">#{r.Post.id}</span></div><h2>{r.Post.title}</h2><p className="post-content">{r.Post.content}</p><div className="author"><span className="avatar">{r.Post.owner.email[0].toUpperCase()}</span><div><span>{r.Post.owner.email}</span><small>{new Date(r.Post.created).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</small></div></div><footer><button className={'vote '+(r.voted?'voted':'')} onClick={()=>vote(r)} disabled={busy} aria-label={r.voted?'Remove vote':'Upvote'}><ArrowUp size={17}/>{r.votes}<span>{r.voted?'Voted':'Vote'}</span></button>{r.Post.owner_id===uid&&<div className="flex"><Button variant="ghost" size="icon" aria-label="Edit post" onClick={()=>compose(r.Post)}><PenLine size={16}/></Button><Button variant="ghost" size="icon" aria-label="Delete post" onClick={()=>setRemove(r.Post)}><Trash2 size={16}/></Button></div>}</footer></article>)}</div>}
 <div className="pagination"><span>{rows.length} posts on this page</span><div><Button variant="ghost" disabled={!page||loading} onClick={()=>setPage(p=>p-1)}>Previous</Button><span>{page+1}</span><Button variant="ghost" disabled={rows.length<12||loading} onClick={()=>setPage(p=>p+1)}>Next</Button></div></div></TabsContent>
 <TabsContent value="explorer"><section className="panel explorer"><h2>Send a real request</h2><p className="muted">Uses the active {base?'JWT session':'sandbox persona'}. Write requests change your saved data.</p><label>Endpoint<Select value={endpoint} onValueChange={setEndpoint}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{['GET /posts/','GET /posts/{id}','POST /posts/','PUT /posts/{id}','DELETE /posts/{id}','POST /vote/','GET /users/me','GET /health'].map(e=><SelectItem key={e} value={e}>{e}</SelectItem>)}</SelectContent></Select></label>{endpoint.includes('{id}')&&<label>Post ID<Input type="number" min="1" value={resourceId} onChange={e=>setResourceId(e.target.value)}/></label>}{/^(POST|PUT)/.test(endpoint)&&<label>JSON body<Textarea className="code-input" value={body} onChange={e=>setBody(e.target.value)} rows={9}/></label>}{endpoint.includes('/vote')&&<p className="muted">Vote body: {'{"post_id": 1, "dir": 1}'}. Use dir 0 to remove.</p>}<Button disabled={busy} onClick={run}><Play size={16}/>Send request</Button></section></TabsContent>
 <TabsContent value="guide"><section className="panel guide"><h2>From learning project to working application.</h2><p>Your original FastAPI project provides users, login, posts, and voting. This workspace makes those flows interactive.</p><h3>Two ways to play</h3><p><strong>Hosted playground:</strong> a JavaScript Worker API with D1 storage. Author and Reader are test personas, not separate login accounts. Your sandbox is isolated by your ChatGPT identity. Switch personas to test editing permissions and private drafts.</p><p><strong>Connect FastAPI:</strong> run the updated Python backend on a Python-capable host, add this dashboard’s origin to CORS_ORIGINS, then connect its HTTPS URL and sign in. All requests go directly from your browser to your backend. Tokens stay in memory and clear on reload.</p><h3>What changed in Python</h3><ul><li>Pydantic 2 settings and schemas; typed SQLAlchemy 2 models and queries.</li><li>Argon2 password hashing, legacy bcrypt upgrades, expiring PyJWT tokens.</li><li>Author-only editing, private drafts, bounded inputs, duplicate handling.</li><li>Docker / PostgreSQL setup, migration support, API tests, and CI.</li></ul><h3>Run the backend locally</h3><pre>cd backend{`\n`}python -m venv .venv{`\n`}pip install -r requirements.txt{`\n`}# Set SECRET_KEY to a random 64-character value{`\n`}python -m app.init_db{`\n`}uvicorn app.main:app --reload</pre><p>SQLite is the development default. For PostgreSQL, use the included Docker Compose configuration and Alembic migrations. See the backend README for deployment details.</p><p><a href="https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/" target="_blank" rel="noreferrer">FastAPI security reference ↗</a></p></section></TabsContent></Tabs></div>
 <aside className="inspector"><div className="inspector-head"><Activity size={17}/><strong>Request inspector</strong><Button size="icon" variant="ghost" aria-label="Clear request log" onClick={()=>setLogs([])}><RefreshCw size={14}/></Button></div><div className="inspector-body">{last?<><div className="request-title"><span className="method">{last.method}</span><code>{last.path.split('?')[0]}</code></div><div className="response-meta"><span className={last.status>=400||last.status===0?'bad':'good'}>{last.status||'Network error'} {last.status>=200&&last.status<300?'OK':''}</span><span>{last.ms} ms</span></div><div className="json-title">RESPONSE BODY<Button size="icon" variant="ghost" aria-label="Copy response" onClick={async()=>{try{await navigator.clipboard.writeText(JSON.stringify(last.data,null,2));toast.success('Response copied')}catch{toast.error('Clipboard unavailable')}}}><Copy size={14}/></Button></div><pre className="json">{JSON.stringify(last.data,null,2)}</pre></>:<div className="inspector-empty"><Code2 size={30}/><p>Your next request lands here.</p><span>Create a post or open the API explorer.</span></div>}</div><div className="history"><span className="eyebrow">THIS SESSION · {logs.length} REQUESTS</span>{logs.slice(0,6).map((l,i)=><button key={i} onClick={()=>setLogs(v=>[v[i],...v.filter((_,j)=>j!==i)])}><span className="method">{l.method}</span><code>{l.path.split('?')[0]}</code><span className={l.status>=400?'bad':'muted'}>{l.status}</span></button>)}</div><p className="inspector-note">Actual responses. Browser round-trip timing.<br/>Login tokens are redacted.</p></aside></div><footer className="site-footer"><span>fastapi studio / kranthivg</span><span>Built to learn. Ready to experiment.</span></footer></main>
 <Dialog open={editor} onOpenChange={setEditor}><DialogContent><DialogHeader><DialogTitle>{edit?'Edit post':'Create a post'}</DialogTitle><DialogDescription>Saved to {base?'your FastAPI backend':'your private sandbox'}.</DialogDescription></DialogHeader><form onSubmit={save} className="form-stack"><label>Title<Input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} placeholder="What are you building?"/></label><label>Content<Textarea required maxLength={20000} rows={6} value={content} onChange={e=>setContent(e.target.value)} placeholder="Write something worth sharing…"/></label><label className="flex items-center gap-3"><Switch checked={published} onCheckedChange={setPublished}/>Published <span className="muted">{published?'Visible to both personas':'Only you can see this draft'}</span></label><Button disabled={busy} type="submit">{busy?'Saving…':edit?'Save changes':'Create post'}</Button></form></DialogContent></Dialog>
 <AlertDialog open={!!remove} onOpenChange={v=>!v&&setRemove(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this post?</AlertDialogTitle><AlertDialogDescription>This removes the post and its votes.</AlertDialogDescription></AlertDialogHeader><AlertDialogCancel>Cancel</AlertDialogCancel><Button variant="destructive" disabled={busy} onClick={async()=>{setBusy(true);try{await api(`/posts/${remove?.id}`,'DELETE');setRemove(null);await refresh();toast.success('Post deleted')}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}}>Delete post</Button></AlertDialogContent></AlertDialog>
 <Dialog open={connect} onOpenChange={setConnect}><DialogContent><DialogHeader><DialogTitle>Connect your FastAPI backend</DialogTitle><DialogDescription>Use a deployed HTTPS backend with this site allowed in its CORS settings.</DialogDescription></DialogHeader><form className="form-stack" onSubmit={login}><label>API base URL<Input required type="url" placeholder="https://your-api.example.com" value={baseDraft} onChange={e=>setBaseDraft(e.target.value)}/></label><label>Email<Input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<Input required type="password" minLength={signup?12:1} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="flex items-center gap-3"><Switch checked={signup} onCheckedChange={setSignup}/>Create a new account</label><Button disabled={busy}>{busy?'Connecting…':signup?'Register & connect':'Sign in & connect'}</Button><p className="muted text-sm">Credentials go only to the URL you enter. Session tokens are held in memory.</p></form></DialogContent></Dialog>
 </div>
}
